env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended  
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
   import/extensions: 0,
   no-console: 0,
   react/jsx-no-constructed-context-values: 0,
   react/prop-types: 0,
   react/jsx-filename-extension: [1, { extensions: [.js, .jsx] }],
}
